### ISSUE TITLE
Segmentation fault при попытке инициализации log-файла

### ISSUE THREAD

**Issue by Katarn** [QuiteRSS/quiterss2#2]
Собираю на Gentoo с Qt 5.9.1. При запуске приложение валится с Segmentation fault. Валится при обращении к ```mainApp->dataDirPath()``` и содержимое переменной ```m_dataDirPath``` в этот момент такое:

![image](https://user-images.githubusercontent.com/6339978/29143546-4737da14-7d5e-11e7-9551-809a7dcdd788.png)

Это на ```logfile.cpp:39``` текущего содержимого ветки ```master```.

**Comment by Katarn** [comment]
Всё так же падает. Выглядит вот так:

![image](https://user-images.githubusercontent.com/6339978/29157215-86ff2cf6-7dae-11e7-916b-eb368ed43ad1.png)

**Comment by Funcy-dcm** [comment]
Можешь сделать полный вывод. Вижу что в LogFile::msgHandler попадает, а знать бы кто вызвал эту функцию

**Comment by Funcy-dcm** [comment]
Ещё один вариант, но мне кажется избыточным, но он работает в старой версии (тоже была такая проблема)

**Comment by Katarn** [comment]
Исправление помогло. А вот так выглядел полный вывод до того как его накатил:

![image](https://user-images.githubusercontent.com/6339978/29184177-010251b8-7e0e-11e7-9e17-1c127098f93f.png)

Возможно подскажет куда копать чтобы не костылить. Если это, конечно, был костыль.

**Comment by Funcy-dcm** [comment]
Спасибо, примерно понял что происходить. Надо пробовать
Ну не костыль, очень даже хорошее решение, но прежний вариант мне больше нравился и без лишнего кода
