### ISSUE TITLE
Make analytics opt-in by default, or show dialogue(consent) when first launch.

### ISSUE THREAD

**Issue by reportinganalyticz** [QuiteRSS/quiterss2#3]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/QuiteRSS/quiterss/issues
    * Checked that there is not already an QuiteRSS version that provides the described functionality: https://quiterss.org/en/download

### Description

https://github.com/QuiteRSS/quiterss2/blob/8237423104a7983b059402e09724ffc693f12a83/src/3rdparty/ganalytics/ganalytics.cpp

QuiteRSS 2 now have Google Analytics.
I want you to turn it off by default, or show dialogue box(We'd like to collect your info. Will you help? Yes to enable Analytics, No to disable it.) when the user launch this software for the first time.

If you don't do this, you are violating GDPR law and even you are not EU citizen, you must obey it.
Fail to do so will cause law enforcement to knock your door.

**Comment by reportinganalyticz** [comment]
I am using QuiteRSS 0.18.x for a long time.
If you're going to add "data collection(aka Analytics)" code, I will encourage all users to switch to other software.

**Comment by Katarn** [comment]
A few things.

1. The GDPR law, as I understand it, is related to personal data. QuiteRSS does not collect personal data. Also, QuiteRSS is not a legal entity therefore it is not subject to the law.

2. As you can see from the code, it is used only to calculate the number of active users of the application. No data about feeds and other user actions.

3. You use version 0.18, it has been also use analytics for a long time.

> Fail to do so will cause law enforcement to knock your door.

4. No, in Russian Federation territory it's impossible.

I got the impression that you did not understand (or did not read) the provisions of the GDPR. The application does not violate the GDPR in any form. And the ultimatum tone of your message is unpleasant.

But this is not an official response. I'm not an application developer. As an application user, I can give you a hint - you can disable analytics in the .ini-file right now. I also do not like when collect data about me, but I do not mind if the author knows how many people use the results of his works. I did not turn off this setting myself.

**Comment by Funcy-dcm** [comment]
QuiteRSS version 0.x.x "Menu - Tools - Options - Help improve QuiteRSS by sending usage information"
In the future we wanted to make a message output on the first start
