### ISSUE TITLE
Is this project abandoned or does the author simply have no time for it?

### ISSUE THREAD

**Issue by EvolutionPixels** [QuiteRSS/quiterss2#7]
I am curious. Will the development continue or will this project remain in the form in which it is now (unfinished)?

**Comment by Funcy-dcm** [comment]
Unfortunately, there is no free time

**Comment by EvolutionPixels** [comment]
> 
> 
> Unfortunately, there is no free time

I understand you. I hope this project continues to live and develop someday.

**Comment by dodona2** [comment]
I also hope this project continues to live and develop. Its a very good program. The best feed reader!

**Comment by EvolutionPixels** [comment]
> 
> 
> I also hope this project continues to live and develop. Its a very good program. The best feed reader!

 I didn’t say anything bad about this software. 👎 was superfluous.

**Comment by EvolutionPixels** [comment]
Если что, то я из России, Москва. Просто предпочитаю говорить на английском языке на GitHub.

**Comment by Funcy-dcm** [comment]
OK :-)

**Comment by dodona2** [comment]
> I didn’t say anything bad about this software. 👎 was superfluous.
no, it was a mistake, I corrected meanwhile. Sorry.
